rule filter:
    input:
        rds=rules.qc.output.rds
    output:
        plot=paths.filter.plot,
        nfeature=paths.filter.nfeature,
        ncount=paths.filter.ncount,
        mt=paths.filter.mt,
        hb=paths.filter.hb,
        rb=paths.filter.rb,
        nspot=paths.filter.nspot,
        rds=paths.filter.rds
    benchmark:
        "benchmark/{sample}_filter.tab"
    log:
        "log/{sample}_filter.log"
    conda:
        "../envs/seurat.yaml"
    params:
        functions=SOURCEDIR+"/r/functions.R",
        ncount_min=config["filter"]["ncount_min"],
        nfeature_min=config["filter"]["nfeature_min"],
        visium_type=lambda wildcards: image_path(wildcards.sample, "visium_type"),
        bin_size=config["qc"]["bin_size"],
        hla_ig=config["filter"]["hla_ig"],
        mt=config["filter"]["mt"],
        rb=config["filter"]["rb"],
        hb=config["filter"]["hb"]
    script:
        "../source/r/filter.R"
